#!/bin/bash

LEFT="/home/dev/Cyder Docs/6. Projects/Development/custom_addons/hide_qty-unitcost/views/sale_portal_templates.xml"
RIGHT=/opt/odoosrc/16.0/odoo/addons/sale_management/views/sale_portal_templates.xml

echo "< = $LEFT"
echo "> = $RIGHT"
#diff ~/Cyder\ Docs/6.\ Projects/Development/custom_addons/hide_qty-unitcost/views/sale_portal_templates.xml /opt/odoosrc/16.0/odoo/addons/sale_management/views/sale_portal_templates.xml 


diff "$LEFT" "$RIGHT"
